kind: pipeline
type: docker
name: testing
clone:
  recursive: true

environment:
  SVN_PATH: KOMA-SVN

steps:
- name: check-l3build doc
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  pull: if-not-exists
  # detach: true
  commands:
  - l3build doc
- name: compare-koma-script
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  pull: if-not-exists
  settings:
    repo: KOMA-Script/tagging-lab
    tags: latest
    cache_from: "KOMA-Script/tagging-lab:latest"
    dry_run: true
  environment:
    LANG: de_DE.UTF-8
    LC_ALL: de_DE.UTF-8
  commands:
  - export LC_ALL=C
  - rm build.lua
  - mv KOMA-build.lua build.lua
  - l3build check
  - cd $SVN_PATH && cp ../build.lua scrmain.ins . && l3build check && cd -
