scrletter - wrapper class to scrartcl class + scrletter package
------------------------------------------------------------------------------
Maintainer:     Markus Kohm
E-Mail:         komascript at gmx info
Abstract:       scrletter is a wrapper class to class scrartcl with package
                scrletter. Is has been made, to provide a letter class, that
                also supports features like sections and floats.
Requires:       scrartcl.cls  – KOMA-Script class
                scrletter.sty – KOMA-Script package
License:        LPPL 1.3c or later
State:          Author maintained
Version:        !!!THIS WILL BE SET BY THE RELEASE PROCESS!!!
